### ISSUE TITLE
Model ou Controller ?

### ISSUE THREAD

**Issue by edukmattos** [jansenfelipe/utils#4]
Oi, Jansen !
Muito útil o teu pacote !
Parabéns !

Mas estou com uma dificuldade... 
Sou novato no Laravel...

Gostaria de utilizar o teu pacote no Model Members pois atraves de um getter (getCpfMaskAttribute), tentar fazer com que seja formatado com a mascara CPF.

Segue abaixo parte do meu script para verificar se está correto ou não.

<?php

namespace App;

require_once '../vendor/autoload.php'; 

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Venturecraft\Revisionable\Revisionable;
use Carbon\Carbon;
use DB;

use JansenFelipe\Utils\Utils as Utils;
use JansenFelipe\Utils\Mask as Mask;

class Member extends Revisionable
{
    use SoftDeletes;
    protected $dates = [...];

   public function getCpfMaskAttribute($value)
    {
        return Utils::mask($value, Mask::CPF);
    }

}

**Comment by jansenfelipe** [comment]
Ola @ecmattos ! Obrigado!

Se vc instalou o package pelo composer, não tem necessidade do "_require_once '../vendor/autoload.php';_"

Se quiser utilizar no blade, vc vai precisar de adicionar as classes no 'aliases', lá no config/app.php:

``` php
'aliases' => [
        // other aliases ommited
        'Utils' => JansenFelipe\Utils\Utils::class,
        'Mask' => JansenFelipe\Utils\ Mask::class,
],
```

**Comment by edukmattos** [comment]
Ok.
Funcionando perfeitamente !
Muito obrigado.
