### ISSUE TITLE
Novas máscaras

### ISSUE THREAD

**Issue by edukmattos** [jansenfelipe/utils#5]
Se eu quiser acrescentar novas mascaras, como faço ?
Tenho que editar algum arquivo ? E as alteraçoes neste arquivo, permanecerão depois de uma atualização ?

**Comment by jansenfelipe** [comment]
Vc pode utilizar:

``` php
Utils::mask('022016', '##-####'); //02-2016
```

**Comment by edukmattos** [comment]
Ok.
Valeu.
Muito obrigado !
