### ISSUE TITLE
Função para obter o tamanho do arquivo

### ISSUE THREAD

**Issue by tiagocardosos** [jansenfelipe/utils#6]
// call the above humanFileSize function and pass it a number as bytes

echo humanFileSize(8763432); // will echo 8.35 MB
echo humanFileSize(258); // will echo 258 B
echo humanFileSize( filesize('/path/to/some/file'); // will echo out the file size of that file

**Comment by jansenfelipe** [comment]
ótimo! bem útil! Lembra de colocar no readme.md
